export interface MovimientoRegistroDTO {
  tipoMovimiento: TipoMovimiento;
  motivo: string;
  referenciaId: string;
}

export enum TipoMovimiento {
  // LOTES
  REGISTRO_LOTE = "REGISTRO_LOTE",
  LOTE_AGOTADO = "LOTE_AGOTADO",
  REACTIVACION_LOTE = "REACTIVACION_LOTE",
  CAMBIO_FIFO = "CAMBIO_FIFO",

  // VENTAS / COMPLETO
  VENTA = "VENTA",
  ANULACION_VENTA = "ANULACION_VENTA",

  // PRENDAS / COMPLETO
  REGISTRO_PRENDA = "REGISTRO_PRENDA",
  MODIFICACION_PRENDA = "MODIFICACION_PRENDA",
  CAMBIO_ESTADO_PRENDA = "CAMBIO_ESTADO_PRENDA",
  PRENDA_AGOTADA = "PRENDA_AGOTADA",
  INHABILITACION_PRENDA = "INHABILITACION_PRENDA",
  REACTIVACION_PRENDA = "REACTIVACION_PRENDA",

  // CATEGORÍAS / COMPLETO
  REGISTRO_CATEGORIA = "REGISTRO_CATEGORIA",
  MODIFICACION_CATEGORIA = "MODIFICACION_CATEGORIA",
  INHABILITACION_CATEGORIA = "INHABILITACION_CATEGORIA",
  REACTIVACION_CATEGORIA = "REACTIVACION_CATEGORIA",

  // MARCAS / COMPLETO
  REGISTRO_MARCA = "REGISTRO_MARCA",
  MODIFICACION_MARCA = "MODIFICACION_MARCA",
  INHABILITACION_MARCA = "INHABILITACION_MARCA",
  REACTIVACION_MARCA = "REACTIVACION_MARCA",

  // TALLAS / COMPLETO
  REGISTRO_TALLA = "REGISTRO_TALLA",
  MODIFICACION_TALLA = "MODIFICACION_TALLA",
  INHABILITACION_TALLA = "INHABILITACION_TALLA",
  REACTIVACION_TALLA = "REACTIVACION_TALLA",

  // SISTEMA
  ACCION_ADMINISTRATIVA = "ACCION_ADMINISTRATIVA",
  CORRECCION_MANUAL = "CORRECCION_MANUAL"
}
